.TH ZSD 6 "July 21, 2013" "ZSD(6)" "INOVA TECHNOLOGY"
.SH NAME
.B zsd
\- Zombie Smack Down!
.SH SYNOPSIS
.B zsd
[\fB\-h\fR]
[\fB\-i\fR]
[\fB\-s\fR]
[\fB\-u\fR]
.SH AVAILABILITY
Right now,
.B zsd
only runs on OS X, with ruby 1.9.2 or higher
.SH DESCRIPTION
.B zsd
is a text-based, zombie fighting game.
.PP
To play, just run
.B zsd
without any arguments, but following options can be used
.TP
.BR \-h
Displays help, then exits.
.PP
.TP
.BR \-i
Shows game info, without starting the game.
.PP
.TP
.BR \-s
Shows top 5 highscores on your machine, then exits.
.PP
.TP
.BR \-u
Updates the game, then exits.
.SH AUTHORS
Addison Bean, Chase Weimer
.SH FILES
All file relating to
.B zsd
are in the directory ~/.zsd
.SH BUGS
Hopfully none. If bugs are found, please open an issue on Github at https://github.com/INOVA-Technology/Zombie-Smack-Down/issues
.SH SEE ALSO
The source code, installer, and other crap is at
.PP
https://github.com/INOVA-Technology/Zombie-Smack-Down
.PP
For more info on how to play, run
.B zsd -h