#!/usr/bin/env ruby

$rpath = "#{File.expand_path '~'}/.zsd"

require "optparse"
$options = []

OptionParser.new { |opts|

	opts.on("-i", "--info", "Shows info on current game") {
		$options << "i"
	}

	opts.on("-h", "--help", "Shows help page") {
		$options << "h"
	}

	opts.on("-s", "--scores", "Shows top 5 high scores") {
		$options << "s"
	}

	opts.on("-u", "--update", "Updates zsd") {
		$options << "u"
	}

	opts.on("-t", "--testing", "For dev use only") {
		$rpath = "."
	}

}.parse!

require "#{$rpath}/require/other"

def main

	cli = Cli.new

	unless $options.empty?
		$options.each { |o|
			case o
			when "i"
				cli.player.info
				exit
			when "h"
				cli.tutorial
				exit
			when "s"
				cli.scores
				exit
			when "u"
				system "~/.zsd/update.sh"
				exit
			end
		}
	end

	%w[ TERM INT HUP ].each { |signal|
		trap(signal) {
			exit_game $player
		}
	}

	start cli
end

def start cli

	puts (pInfo "Type help for help.")

	loop {

		cli.spawn_zombie

		while cli.zombie.isAlive
			input = prompt(">").split
			command = input[0]

			if cli.available_commands.include? command
				cli.send command, *input[1..-1]
			else
				puts (pWarn "Unknown Command.") unless command.nil?
			end

		end # zombie has died if loop ends

	} # end game loop

end

if __FILE__ == $0
	main
end