#!/usr/bin/env ruby

if ARGV[0] == '-t'
  require "./ZSDFiles/game"
elsif ARGV[0] == '-u'
  system "curl -s https://raw.github.com/Addisonbean/Zombie-Smack-Down/master/ZSD > /usr/local/bin/ZSD"
  system "curl -s https://raw.github.com/Addisonbean/Zombie-Smack-Down/master/ZSDFiles/game.rb > /usr/local/bin/ZSDFiles/game.rb"
  puts "\e[35mUpdate successful!\e[39m"
  exit
else
  require "/usr/local/bin/ZSDFiles/game"
end
require "readline"

# def prompt promptBegining
#   begin
#     print promptBegining
#     inText = Readline.readline.squeeze(" ").strip.downcase
#     inText
#   rescue Interrupt
#     puts
#     exit
#   end
# end

def start hero
  yep = ["punch", "kick", "combo", "heal", "combolist", "info", "quit", "taunt"]

  while true
  	case hero.prefs[:kills]
  	when 0, 1, 2
  		e = Stuff::Zombie.new hero
    when 3, 4, 5
      e = Stuff::BigZombie.new hero
    when 6, 7, 8
      e = Stuff::DaddyZombie.new hero
    when 9, 10, 11
      e = Stuff::GunZombie.new hero
    when 12, 13, 14
      e = Stuff::NinjaZombie.new hero 
    when 15, 16, 17
      e = Stuff::IdiotZombie.new hero 
    when 18, 19, 20 
      e = Stuff::BlindZombie.new hero 
    when 21, 22, 23 
      e = Stuff::StrongZombie.new hero
    when 24, 25, 26
      e = Stuff::BasicallyDeadZombie.new hero
    else
      hero.win
      break
    end

  	while e.is_alive
  		puts "Type any of the following: " + yep.join(", ")

      input = prompt "> "

  		case input
  		when "punch"
        hero.attack e, "punch"
        e.attack
      when "kick"
        hero.attack e, "kick"
        e.attack
      when "info"
      	hero.info
        e.info
      when "quit"
      	hero.quit
      when "combolist"
        hero.comboList
      when "combo"
      	hero.attack e, "combo"
      	e.attack if hero.r != 0
      when "heal"
      	hero.heal
      when "taunt"
        hero.taunt
      when "easter egg"
        x = Random::rand(-175..150)
        hero.give_xp x
        puts "\e[33mBraaaiiiiinnnnsss!\e[39m (plus #{x} xp)"
      else
      	puts "Input invalid"
        puts input
      end
    end
			
  end
end

def main
	game = Stuff::Game.new

	start game
end

if __FILE__ == $0
	main
end